name: Process and Resize Photos
on:
  push:
    paths: ['**.jpg', '**.jpeg']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python_version: '3.9'}
      - run: pip install Pillow
      - run: python process_photos.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Пытаемся забрать изменения от пользователя, если они были
          git pull --rebase origin main
          git commit -m "Update photo data" || exit 0
          git push
